spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/account_service_db
    username: postgres
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8081